import { Router } from "express";
import organizationMisRoutes from "./modules/mis/organizations/organizations.routes.js";
import deviceMisRoutes from "./modules/mis/devices/devices.routes.js";
import organizationRegistrationRoutes from "./modules/registration/organizations/organizations.routes.js";
import deviceRegistrationRoutes from "./modules/registration/devices/devices.routes.js";
import distributorRegistrationRoutes from "./modules/registration/distributor/distributors.routes.js";
import dashboardRoutes from "./modules/dashboard/dashboard.routes.js";
import newTicketRoutes from "./modules/serviceAndSupport/supportTicket/newTicket/newTicket.routes.js";
import updateTicketRoutes from "./modules/serviceAndSupport/supportTicket/updateTicket/updateTicket.routes.js";
import serviceDashboardRoutes from "./modules/serviceAndSupport/supportTicket/serviceDashboard/service.routes.js";
import newFeedbackRoutes from "./modules/serviceAndSupport/customerFeedback/newFeedback/newFeedback.routes.js";
import updateFeedbackRoutes from "./modules/serviceAndSupport/customerFeedback/updateFeedback/updateFeedback.routes.js";
import feedbackDashboardRoutes from "./modules/serviceAndSupport/customerFeedback/feedbackDashboard/feedback.routes.js";
import analyticsDashboardRoutes from "./modules/analytics/analytics.routes.js";
import OrganizationDetailsRoutes from "./modules/mis/organizations/organizationDetails/organizationDetails.rotue.js";
import { authenticate } from "./middleware/auth.middleware.js";
import loginRoutes from "./modules/login/login.routes.js";
import { authorizeRoles } from "./middleware/role.middleware.js";
import  deregisterRoutes  from "./modules/deregister/deregister/deregister.routes.js";
import  revenueRoutes  from "./modules/revenue/revenue.routes.js";
import  clinicalAnalysisRoutes  from "./modules/clinicalAnalysis/clinicalAnalysis.routes.js";
const router = Router();

router.use("/auth", loginRoutes);
router.use(authenticate);
router.use("/deregister", authenticate, authorizeRoles("admin"),deregisterRoutes);
router.use("/mis/organizations", authorizeRoles("admin", "groupUser"), organizationMisRoutes);
router.use("/mis/devices", authorizeRoles("admin", "groupUser"), deviceMisRoutes);
router.use("/registration/organizations", authorizeRoles("admin"), organizationRegistrationRoutes);
router.use("/registration/devices", authorizeRoles("admin"), deviceRegistrationRoutes);
router.use("/registration/distributors", authorizeRoles("admin"), distributorRegistrationRoutes);
router.use("/dashboard", authorizeRoles("admin", "groupUser"), dashboardRoutes);
router.use("/support", authorizeRoles("admin"), newTicketRoutes);
router.use("/support", authorizeRoles("admin"), updateTicketRoutes);
router.use("/support", authorizeRoles("admin"), serviceDashboardRoutes);
router.use("/feedback", authorizeRoles("admin"), newFeedbackRoutes);
router.use("/feedback", authorizeRoles("admin"), updateFeedbackRoutes);
router.use("/feedback", authorizeRoles("admin"), feedbackDashboardRoutes);
router.use("/revenue", authorizeRoles("admin"), revenueRoutes);
router.use("/analytics", authorizeRoles("admin", "groupUser"), analyticsDashboardRoutes);
router.use("/organizationDetails", authorizeRoles("admin", "groupUser"), OrganizationDetailsRoutes);
router.use("/clinical", authorizeRoles("admin", "groupUser"), clinicalAnalysisRoutes);

export default router;